- name: Instalar Nginx
  yum:
    name: nginx
    state: present

- name: Asegurar que Nginx está iniciado
  service:
    name: nginx
    state: started
    enabled: true

- name: Copiar página de prueba
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
