# - name: Instalar dependencias para SSM
#   apt:
#     name:
#       - curl
#       - wget
#       - unzip
#     state: present
#     update_cache: yes

# - name: Descargar agente de SSM
#   get_url:
#     url: https://s3.eu-west-1.amazonaws.com/amazon-ssm-eu-west-1/latest/debian_amd64/amazon-ssm-agent.deb
#     dest: /tmp/amazon-ssm-agent.deb

# - name: Instalar agente de SSM
#   apt:
#     deb: /tmp/amazon-ssm-agent.deb

# - name: Habilitar y arrancar el agente SSM
#   systemd:
#     name: amazon-ssm-agent
#     enabled: yes
#     state: started

- name: Instalar paquetes necesarios
  apt:
    name: 
      - docker.io
      - unzip
      - mariadb-client
    state: present
    update_cache: yes

- name: Habilitar y arrancar Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Crear directorio para WordPress
  file:
    path: /opt/wordpress
    state: directory

- name: Copiar tema OceanWP a la instancia
  copy:
    src: oceanwp.zip
    dest: /opt/wordpress/oceanwp.zip

- name: Crear contenedor WordPress con volumen persistente
  docker_container:
    name: wordpress
    image: wordpress:latest
    ports:
      - "80:80"
    env:
      WORDPRESS_DB_HOST: "{{ db_host }}"
      WORDPRESS_DB_NAME: "{{ db_name }}"
      WORDPRESS_DB_USER: "{{ db_user }}" 
      WORDPRESS_DB_PASSWORD: "{{ db_password }}"
    volumes:
      - wordpress_data:/var/www/html
    restart_policy: always

- name: Esperar a que WordPress esté listo (ping al puerto 80)
  wait_for:
    port: 80
    delay: 10
    timeout: 60

- name: Descargar WP-CLI
  shell: docker exec wordpress curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

- name: Dar permisos de ejecución a WP-CLI
  shell: docker exec wordpress chmod +x wp-cli.phar

- name: Mover WP-CLI a /usr/local/bin/wp
  shell: docker exec wordpress mv wp-cli.phar /usr/local/bin/wp

- name: Verificar instalación de WP-CLI
  shell: docker exec wordpress wp --info


- name: Crear directorio destino para descomprimir OceanWP
  file:
    path: /opt/wordpress/oceanwp
    state: directory

- name: Extraer tema OceanWP en la instancia
  unarchive:
    src: /opt/wordpress/oceanwp.zip
    dest: /opt/wordpress/oceanwp
    remote_src: yes

- name: Copiar tema descomprimido al contenedor
  shell: docker cp /opt/wordpress/oceanwp/oceanwp wordpress:/var/www/html/wp-content/themes/

# - name: Instalar WordPress si no está instalado
#   shell: >
#     docker exec wordpress wp core is-installed --allow-root ||
#     docker exec wordpress wp core install
#     --url=http://localhost
#     --title="{{ wp_title }}"
#     --admin_user={{ wp_admin_user }}
#     --admin_password={{ wp_admin_password }}
#     --admin_email={{ wp_admin_email }}
#     --skip-email
#     --allow-root

